package abstractFactory;

public enum TipEveniment {
	HACKATHON_BUSINESS_INTELLIGENCE, HACKATHON_DEZVOLTARE, HACKATHON_ANALIZA_DATE,
	WORKSHOP_TEHNOLOGIE, WORKSHOP_SANATATE, WORKSHOP_MEDIU,
	ALGORITMICA_INCEPATOR, ALGORITMICA_MEDIU, ALGORITMICA_AVANSAT
}
